// Cardápio padrão — usado como reserva se o Supabase não estiver configurado
// e como semente inicial da tabela na primeira vez que o painel abre.
// A partir daí, tudo é lido/salvo no Supabase e editado pelo admin.html.
//
// OBS: os preços abaixo são apenas um ponto de partida. Ajuste cada item
// (preço, foto, disponibilidade) pelo painel administrativo (admin.html).
const FALLBACK_PRODUCTS = [
  {
    id: "m1",
    name: "Marmita de Calabresa",
    category: "Marmitas do Dia",
    price: 18.0,
    image: "assets/products/calabresa.jpg",
    description: "Calabresa acebolada, arroz, feijão tropeiro, salada e farofa.",
    available: true,
  },
  {
    id: "m2",
    name: "Marmita de Omelete",
    category: "Marmitas do Dia",
    price: 17.0,
    image: "assets/products/omelete.jpg",
    description: "Omelete caseiro, arroz, feijão, salada e farofa.",
    available: true,
  },
  {
    id: "m3",
    name: "Marmita de Bisteca Suína",
    category: "Marmitas do Dia",
    price: 20.0,
    image: "assets/products/bisteca-suina.jpg",
    description: "Bisteca suína grelhada, arroz, feijão, salada e farofa.",
    available: true,
  },
  {
    id: "m4",
    name: "Marmita de Frango à Passarinho",
    category: "Marmitas do Dia",
    price: 19.0,
    image: "assets/products/frango-a-passarinho.jpg",
    description: "Frango à passarinho crocante, arroz, feijão, salada e farofa.",
    available: true,
  },
  {
    id: "m5",
    name: "Marmita de Filé de Frango",
    category: "Marmitas do Dia",
    price: 19.0,
    image: "assets/products/file-de-frango.jpg",
    description: "Filé de frango grelhado, arroz, feijão, salada e farofa.",
    available: true,
  },
  {
    id: "m6",
    name: "Marmita de Bife Acebolado",
    category: "Marmitas do Dia",
    price: 20.0,
    image: "assets/products/bife-acebolado.jpg",
    description: "Bife acebolado, arroz, feijão, salada e farofa.",
    available: true,
  },
  {
    id: "m7",
    name: "Marmita de Contra Filé Acebolado",
    category: "Marmitas do Dia",
    price: 24.0,
    originalPrice: 27.0,
    image: "assets/products/contra-file-acebolado.jpg",
    description: "Contra filé acebolado, arroz, feijão, salada e farofa.",
    available: true,
  },
  {
    id: "p1",
    name: "Porção de Frango à Passarinho",
    category: "Porções",
    price: 39.9,
    image: "",
    description: "Porção generosa de frango à passarinho. Serve bem 2 pessoas.",
    available: true,
  },
  {
    id: "p2",
    name: "Porção de Calabresa Acebolada",
    category: "Porções",
    price: 34.9,
    image: "",
    description: "Calabresa acebolada na chapa. Serve bem 2 pessoas.",
    available: true,
  },
  {
    id: "p3",
    name: "Porção de Batata Frita",
    category: "Porções",
    price: 24.9,
    image: "",
    description: "Batata frita crocante. Serve bem 2 pessoas.",
    available: true,
  },
  {
    id: "b1",
    name: "Refrigerante Lata 350ml",
    category: "Bebidas",
    price: 6.0,
    image: "",
    description: "Coca-Cola, Guaraná ou Fanta. Consulte os sabores disponíveis.",
    available: true,
  },
  {
    id: "b2",
    name: "Suco Natural 500ml",
    category: "Bebidas",
    price: 9.0,
    image: "",
    description: "Suco natural do dia. Consulte o sabor.",
    available: true,
  },
];
